### ISSUE TITLE
간단 코드 리뷰

### ISSUE THREAD

**Issue by flynnpark** [rae-han/lecture-netflix-clone#1]
안녕하세요 래한님~~ 약속대로 코드리뷰 하러 왔습니다! 간단하게 적어볼테니 가볍게 봐주세요!

윗줄 쓰고 프로젝트를 쭉 봤는데, 폴더 구조도 너무 좋고, 로직 분리도 너무 잘 되어 있네요. 딱 한 가지 아쉬운 점이라면 사용하지 않은 코드 안 지운 것 정도 있겠는데, 이거야 뭐 나중에 필요해서 남겨두신 거라고 생각하면 제가 따로 이야기할 게 없는 것 같아요.

`/test` 라우트는 진짜 테스트를 위한 것이었을까요!?

저는 추가적으로 `/movies/{movieId}`로 모달 구현 한 번 해보시는 걸 요청드리고 싶습니다 ㅎㅅㅎ 2개 path로 다 처리할 수 있을 것 같거든요!

넘 잘 짜여진 코드 잘 봤습니다... 감사해요~

**Comment by rae-han** [comment]
@flynnpark 봐주셔서 감사합니다!!

사실 사용하지 않는 코드들을 제가 꼼꼼하게 지우지 않았습니다. /test 라우트도 거기서 뭔가 해본 뒤 돼서 다른 곳으로 코드를 옮겼는데 그 과정에서 그냥 남겨뒀네요. 그런 부분 신경 쓰는게 디테일이고 습관이 되면 좋은데 아직 많이 부족하네요ㅠ 세심하게 봐주셔서 감사합니다.
안그래도 이번주 목금요일에 다른분들 코드 보고 배운 것들 적용해보려고 했는데 그때 꼭 해보겠습니다. 특히 플린님 코드 보고 많이 배웠습니다. 감사합니다.

리뷰 해주셔서 감사합니다!!
